### ISSUE TITLE
[QST] [API] Should dask-cugraph `md_pagerank` just be `pagerank`?

### ISSUE THREAD

**Issue by afender** [rapidsai/dask-cugraph#29]
I would suggest the following : 
```
  import dask_cugraph
  ...
  pr = dask_cugraph.pagerank(ddf, ... )
```

Any risk that this `pagerank` conflicts with the SNMG PageRank in cuGraph module? If not, I think we should just go with `pagerank` instead of `mg_pagerank`.

Notice that we currently do :
```
    import dask_cugraph.pagerank 
    pr = dask_cugraph.pagerank.mg_pagerank(ddf)
```
The PageRank keyword appears twice when calling the feature. Could we do something closer to cuGraph API such as the proposal above?

**Comment by afender** [comment]
+ @rgsl888prabhu

**Comment by ramakrishnap-nv** [comment]
As per my knowledge, we might have to move the `pagerank.py` file to the top directory `dask_cugraph/dask_cugraph/` rather than `dask_cugraph/dask_cugraph/pagerank`.

The other option is adding

`from .pagerank import mg_pagerank, read_csv`

in `dask_cugraph/__init__.py`

this will enable us to use it as `from dask_cugraph import mg_pagerank` 

or 

`import dask_cugraph`
`dask_cugraph.mg_pagerank(ddf)`

but this will fail `import dask_cugraph.mg_pagerank as pg`

**Comment by afender** [comment]
updated
